config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :products, :managers, :clients, :orders
  get 'orders/:id/make' => 'orders#make', as: :make_order

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, :phone, :email, presence: true

  has_many :orders
  belongs_to :manager

  has_many :client_managers
  # , dependent: :destroy
end

app/models/client_manager.rb
class ClientManager < ActiveRecord::Base
  belongs_to :client
  belongs_to :manager
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  validates :name, :phone, :email, presence: true

  has_many :clients
  has_many :client_managers
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :manager, :client, presence: true

  belongs_to :client
  belongs_to :manager
  has_many :positions
  has_many :products, through: :positions

  scope :maked, -> { where(state: 'готов') }

  def calc_price
    positions.map(&:calc_price).sum
  end

#   def make_order_workbook
#
#     book = Spreadsheet::Workbook.new
#
#     sheet1 = book.create_worksheet
#     sheet2 = book.create_worksheet :name => 'Заказ'
#
#     sheet1.name = 'Заказ номер:', order.id
#
#     sheet1.row(0).concat %w{Name Country Acknowlegement}
#     sheet1[1,0] = 'Japan'
#     row = sheet1.row(1)
#     row.push 'Creator of Ruby'
#     row.unshift 'Yukihiro Matsumoto'
#     sheet1.row(2).replace [ 'Daniel J. Berger', 'U.S.A.',
#                           'Author of original code for Spreadsheet::Excel' ]
#     sheet1.row(3).push 'Charles Lowe', 'Author of the ruby-ole Library'
#     sheet1.row(3).insert 1, 'Unknown'
#     sheet1.update_row 4, 'Hannes Wyss', 'Switzerland', 'Author'
#
#     sheet1.row(0).height = 18
#     format = Spreadsheet::Format.new :color => :blue,
#                                    :weight => :bold,
#                                    :size => 18
#     sheet1.row(0).default_format = format
#
#     bold = Spreadsheet::Format.new :weight => :bold
#     4.times do |x| sheet1.row(x + 1).set_format(0, bold) end
#
#     book.write '/path/to/output/excel-file.xls'
#   end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  def calc_price
    quantity * product.price
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :price, numericality: { greater_than: 0, allow_nill: true }
  validates :name, :type_of_product, :price, :description, presence: true

  has_many :positions
  has_many :orders, through: :positions

  def how_need
    positions.pluck(:quantity).sum
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/client_managers_controller.rb
class ClientManagersController < ApplicationController

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
  before_filter :authenticate_user!
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    render text: "Страница не найдена", status: 404 unless @client
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path(@client)
    else
      render 'new'
    end
  end

  def update
    @client.update_attributes(client_params)
    if @client.save
      redirect_to clients_path(@client)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to action: 'index' if @client.destroy
  end

  private

  def client_params
    params.require(:client).permit(:name, :phone, :email)
  end

  def find_client
    @client = Client.find(params[:id])
  end

  def check_if_admin
    # render text: "Access denied", status: 403 unless params[:admin]
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :find_manager, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
  before_filter :authenticate_user!

  def index
    @managers = Manager.all
  end

  def show
    @manager = Manager.find(params[:id])
    render text: "Страница не найдена", status: 404 unless @manager
  end

  def new
    @manager = Manager.new
  end

  def edit
    @manager = Manager.find(params[:id])
  end

  def create
    @manager = Manager.new(manager_params)
    if @manager.save
      redirect_to managers_path(@manager)
    else
      render 'new'
    end
  end

  def update
    @manager.update_attributes(manager_params)
    if @manager.save
      redirect_to managers_path(@manager)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to action: 'index' if @manager.destroy
  end

  private

  def manager_params
    params.require(:manager).permit(:name, :phone, :email)
  end

  def find_manager
    @manager = Manager.find(params[:id])
  end

  def check_if_admin
    # render text: "Access denied", status: 403 unless params[:admin]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @orders = Order.maked
  end

  def show
    @order = Order.find_by_id(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find_by_id(params[:id])
    @position = Position.new
  end

  def create
    @order = Order.new(order_params)
    @order.state = 'не готов'
    if @order.save
      redirect_to edit_order_path(@order)
    else
      render 'new'
    end
  end

  def update
    @order = Order.find_by_id(params[:id])
    if @order.state == 'не готов'
      @position = Position.new(position_params)
      @order.positions << @position

      if @order.save
        redirect_to edit_order_path(@order)
      else
        render 'edit'
      end
    end
  end

  def destroy
  end

  def make
    @order = Order.find_by_id(params[:id])
    @order.order_price = @order.calc_price
    @order.state = 'готов'
    @order.maked_time = DateTime.now
    if @order.save
      redirect_to action: 'index'
    else
      render 'edit'
    end

  end

  private

  def order_params
    params.require(:order).permit(:manager_id, :client_id)
  end

  def position_params
    params.require(:position).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    render text: "Страница не найдена", status: 404 unless @product
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path(@product)
    else
      render 'new'
    end
  end

  def update
    @product.update_attributes(product_params)
    if @product.save
      redirect_to products_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to action: 'index' if @product.destroy
  end

  private

  def product_params
    params.require(:product).permit(:name, :type_of_product, :price, :description)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def check_if_admin
    # render text: "Access denied", status: 403 unless params[:admin]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_managers_helper.rb
module ClientManagersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/edit.html.slim
= simple_form_for @client do |f|
  = f.input :name, label: 'Имя'
  = f.input :phone, label: 'Телефон'
  = f.input :email, label: 'Почта'
  = f.submit 'Сохранить клиента', class: 'btn btn-primary'

app/views/clients/index.html.slim
h1 Клиенты
- if @clients.empty?
  h3 Нет клиентов
  = link_to "Добавить клиента", new_client_path, class: 'btn btn-primary'
- else
  table.table.table-striped
    tr
      th Имя
      th Телефон
      th Почта
      th 
        = link_to "Добавить клиента", new_client_path, class: 'btn btn-primary'
    
    
    - @clients.each do |i|
      tr
        td= link_to i.name, client_path(i)
        td= i.phone
        td= i.email
        td
          div.btn-group style='width: 450px;'
            = link_to "Изменить информацию клиента", edit_client_path(i), class: 'btn btn-warning'
            = link_to "Удалить клиента", i, method: :delete, data: { confirm: "Вы уверены?"}, class: 'btn btn-danger'
          
            
            
    

app/views/clients/new.html.slim
= simple_form_for @client do |f|
  = f.input :name, label: 'Имя'
  = f.input :phone, label: 'Телефон'
  = f.input :email, label: 'Почта'
  = f.submit 'Создать клиента', class: 'btn btn-primary'

app/views/clients/show.html.slim
h1= @client.name
p= "Имя: #{@client.name}"
p= "Телефон: #{@client.phone}"
p= "Почта: #{@client.email}"

app/views/managers/edit.html.slim
= simple_form_for @manager do |f|
  = f.input :name, label: 'Имя'
  = f.input :phone, label: 'Телефон'
  = f.input :email, label: 'Почта'
  = f.submit 'Сохранить менеджера', class: 'btn btn-primary'

app/views/managers/index.html.slim
h1 Менеджеры

- if @managers.empty?
  h3 Нет менеджеров
  = link_to "Добавить менеджера", new_manager_path, class: 'btn btn-primary'
- else
  table.table.table-striped
    tr
      th Имя
      th Телефон
      th Почта
      th 
        = link_to "Добавить менеджера", new_manager_path, class: 'btn btn-primary'
    
    
    - @managers.each do |i|
      tr
        td= link_to i.name, manager_path(i)
        td= i.phone
        td= i.email
        td
          div.btn-group style='width: 500px;'
            = link_to "Изменить информацию менеджера", edit_manager_path(i), class: 'btn btn-warning'
            = link_to "Удалить менеджера", i, method: :delete, data: { confirm: "Вы уверены?"}, class: 'btn btn-danger'
          
            
            
    

app/views/managers/new.html.slim
= simple_form_for @manager do |f|
  = f.input :name, label: 'Имя'
  = f.input :phone, label: 'Телефон'
  = f.input :email, label: 'Почта'
  = f.submit 'Создать менеджера', class: 'btn btn-primary'

app/views/managers/show.html.slim
h1= @manager.name
p= "Имя: #{@manager.name}"
p= "Телефон: #{@manager.phone}"
p= "Почта: #{@manager.email}"

app/views/orders/edit.html.slim
= simple_form_for @order do |f|
  = simple_fields_for @position do |i|
    = i.association :product, label: 'Продукт'
    = i.input :quantity, label: 'Количество'
  = f.submit

- unless @order.positions.empty?
  br

table.table.table-striped
  tr
    th Название
    th Количество
    th

  - @order.positions.each do |i|
    tr
      td= i.product.name
      td= i.quantity
      td
        div.btn-group style='width: 286px;'
            / = link_to "Изменить продукт", edit_position_path(i), class: 'btn btn-warning'

= link_to 'Оформить заказ', make_order_path(@order), class: 'btn btn-success'

app/views/orders/index.html.slim
h1 Заказы
=link_to 'Создать заказ', new_order_path, class: 'btn btn-primary'
br
br
- if @orders.empty?
  h3 Нет заказов
- else
  table.table.table-striped
    tr
      th Менеджер
      th Клиент
      th Описание
      th Цена
      th Время заказа
      th
    
    - @orders.each do |i|
      tr
        td= i.manager.name
        td= i.client.name
        td= i.products.pluck(:name).join(', ')
        td= i.order_price
        td= i.maked_time
        td= link_to "Показать", order_path(i), class: 'btn btn-primary'

app/views/orders/new.html.slim
= simple_form_for @order do |f|
  = f.association :manager, label: 'Менеджер'
  = f.association :client, label: 'Клиент'
  = f.submit 'Создать заказ', class: 'btn btn-primary'
  

app/views/orders/show.html.slim
h1= @order.maked_time
p= "Клиент: #{@order.client.name}"
p= "Менеджер: #{@order.manager.name}"
p= "Сумма заказа: #{@order.order_price} Руб"

table.table.table-striped
  tr
    th Название
    th Тип
    th Цена
    th Количество
  - @order.positions.each do |i|
    tr
      td= link_to i.product.name, product_path(i.product)
      td= i.product.type_of_product
      td= i.product.price
      td= i.quantity
      
  button.btn.btn-primary.hidden-print onclick="window.print();" Печать
  br
  br

app/views/products/edit.html.slim
= simple_form_for @product do |f|
  = f.input :name, label: 'Имя'
  = f.input :type_of_product, label: 'Тип'
  = f.input :price, label: 'Цена'
  = f.input :description, label: 'Описание'
  = f.submit 'Сохранить продукт', class: 'btn btn-primary'

app/views/products/index.html.slim
h1 Продукция

- if @products.empty?
  h3 Нет продукции
- else
- if user_signed_in?
  = link_to "Добавить продукт", new_product_path, class: 'btn btn-primary'
br
br
  
  table.table.table-striped
    tr
      th Название
      th Тип
      th Цена
      th Описание
      th 
    
    
    - @products.each do |i|
      tr
        td= link_to i.name, product_path(i)
        td= i.type_of_product
        td= i.price
        td= i.description
        td
          div.btn-group style='width: 400px;'
          - if user_signed_in?
            = link_to "Изменить продукт", edit_product_path(i), class: 'btn btn-warning'
            = link_to "Удалить продукт", i, method: :delete, data: { confirm: "Вы уверены?"}, class: 'btn btn-danger'
          - else
            
            
    
  

app/views/products/new.html.slim
= simple_form_for @product do |f|
  = f.input :name, label: 'Название'
  = f.input :type_of_product, label: 'Тип'
  = f.input :price, label: 'Цена'
  = f.input :description, label: 'Описание'
  = f.submit 'Создать продукт', class: 'btn btn-primary'

app/views/products/show.html.slim
h1= @product.name
p= "Тип: #{@product.type_of_product}"
p= "Цена: #{@product.price}"
p= "Описание: #{@product.description}"

app/views/welcome/index.html.slim
h1 Welcome
p Курсовая работа Шамрова Никиты Владимировича, студента группы ИТб-122.