config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :products, :managers, :clients, :orders
  get 'orders/:id/make' => 'orders#make', as: :make_order

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, :phone, :email, presence: true

  has_many :orders
  belongs_to :manager

  has_many :client_managers
  # , dependent: :destroy
end

app/models/client_manager.rb
class ClientManager < ActiveRecord::Base
  belongs_to :client
  belongs_to :manager
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  validates :name, :phone, :email, presence: true

  has_many :clients
  has_many :client_managers
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :manager, :client, presence: true

  belongs_to :client
  belongs_to :manager
  has_many :positions
  has_many :products, through: :positions

  scope :maked, -> { where(state: 'готов') }

  def calc_price
    positions.map(&:calc_price).sum
  end

#   def make_order_workbook
#
#     book = Spreadsheet::Workbook.new
#
#     sheet1 = book.create_worksheet
#     sheet2 = book.create_worksheet :name => 'Заказ'
#
#     sheet1.name = 'Заказ номер:', order.id
#
#     sheet1.row(0).concat %w{Name Country Acknowlegement}
#     sheet1[1,0] = 'Japan'
#     row = sheet1.row(1)
#     row.push 'Creator of Ruby'
#     row.unshift 'Yukihiro Matsumoto'
#     sheet1.row(2).replace [ 'Daniel J. Berger', 'U.S.A.',
#                           'Author of original code for Spreadsheet::Excel' ]
#     sheet1.row(3).push 'Charles Lowe', 'Author of the ruby-ole Library'
#     sheet1.row(3).insert 1, 'Unknown'
#     sheet1.update_row 4, 'Hannes Wyss', 'Switzerland', 'Author'
#
#     sheet1.row(0).height = 18
#     format = Spreadsheet::Format.new :color => :blue,
#                                    :weight => :bold,
#                                    :size => 18
#     sheet1.row(0).default_format = format
#
#     bold = Spreadsheet::Format.new :weight => :bold
#     4.times do |x| sheet1.row(x + 1).set_format(0, bold) end
#
#     book.write '/path/to/output/excel-file.xls'
#   end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  def calc_price
    quantity * product.price
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :price, numericality: { greater_than: 0, allow_nill: true }
  validates :name, :type_of_product, :price, :description, presence: true

  has_many :positions
  has_many :orders, through: :positions

  def how_need
    positions.pluck(:quantity).sum
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
  before_filter :authenticate_user!
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    render text: "Страница не найдена", status: 404 unless @client
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path(@client)
    else
      render 'new'
    end
  end

  def update
    @client.update_attributes(client_params)
    if @client.save
      redirect_to clients_path(@client)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to action: 'index' if @client.destroy
  end

  private

  def client_params
    params.require(:client).permit(:name, :phone, :email)
  end

  def find_client
    @client = Client.find(params[:id])
  end

  def check_if_admin
    # render text: "Access denied", status: 403 unless params[:admin]
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :find_manager, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
  before_filter :authenticate_user!

  def index
    @managers = Manager.all
  end

  def show
    @manager = Manager.find(params[:id])
    render text: "Страница не найдена", status: 404 unless @manager
  end

  def new
    @manager = Manager.new
  end

  def edit
    @manager = Manager.find(params[:id])
  end

  def create
    @manager = Manager.new(manager_params)
    if @manager.save
      redirect_to managers_path(@manager)
    else
      render 'new'
    end
  end

  def update
    @manager.update_attributes(manager_params)
    if @manager.save
      redirect_to managers_path(@manager)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to action: 'index' if @manager.destroy
  end

  private

  def manager_params
    params.require(:manager).permit(:name, :phone, :email)
  end

  def find_manager
    @manager = Manager.find(params[:id])
  end

  def check_if_admin
    # render text: "Access denied", status: 403 unless params[:admin]
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @orders = Order.maked
  end

  def show
    @order = Order.find_by_id(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find_by_id(params[:id])
    @position = Position.new
  end

  def create
    @order = Order.new(order_params)
    @order.state = 'не готов'
    if @order.save
      redirect_to edit_order_path(@order)
    else
      render 'new'
    end
  end

  def update
    @order = Order.find_by_id(params[:id])
    if @order.state == 'не готов'
      @position = Position.new(position_params)
      @order.positions << @position

      if @order.save
        redirect_to edit_order_path(@order)
      else
        render 'edit'
      end
    end
  end

  def destroy
  end

  def make
    @order = Order.find_by_id(params[:id])
    @order.order_price = @order.calc_price
    @order.state = 'готов'
    @order.maked_time = DateTime.now
    if @order.save
      redirect_to action: 'index'
    else
      render 'edit'
    end

  end

  private

  def order_params
    params.require(:order).permit(:manager_id, :client_id)
  end

  def position_params
    params.require(:position).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :destroy]
  before_action :check_if_admin, only: [:edit, :update, :new, :create, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    render text: "Страница не найдена", status: 404 unless @product
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path(@product)
    else
      render 'new'
    end
  end

  def update
    @product.update_attributes(product_params)
    if @product.save
      redirect_to products_path(@product)
    else
      render 'edit'
    end
  end

  def destroy
    redirect_to action: 'index' if @product.destroy
  end

  private

  def product_params
    params.require(:product).permit(:name, :type_of_product, :price, :description)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def check_if_admin
    # render text: "Access denied", status: 403 unless params[:admin]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_managers_helper.rb
module ClientManagersHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "MyProject"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'MyProject', root_path, class: 'navbar-brand'
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to 'Продукция', products_path 
              - if user_signed_in?
                li= link_to 'Менеджеры', managers_path
                li= link_to 'Заказы', orders_path
                li= link_to 'Клиенты', clients_path
                
            ul.nav.navbar-nav.pull-right
              - if user_signed_in?
                li= link_to 'выйти', destroy_user_session_path, method: :delete
              - else
                li= link_to 'войти', new_user_session_path
                li= link_to 'регистрация', new_user_registration_path

    .container
      .row
        .col-lg-10.col-lg-offset-1
          = bootstrap_flash
          = yield
        / .col-lg-3
        /   .well.sidebar-nav
        /     h3 Sidebar
        /     ul.nav.nav-list
        /       li.nav-header Sidebar
        /       li= link_to "Link 1", "/path1"
        /       li= link_to "Link 2", "/path2"
        /       li= link_to "Link 3", "/path3"
    div.navbar-fixed-bottom
      hr
      div.navbar-inner.container
        footer
          p &copy; Shamrov Nikita ITb-122 2016